name: CI

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Setup Dependencies
        run: | 
          composer install --ignore-platform-reqs
          npm install

        # - name: Setup Dependencies
        #   uses: "ramsey/composer-install@v2"

      - name: Setup Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Building frontend dependencies
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
