name: Deploy FTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: npm install

      - name: Building the project
        run: npm run production

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: composer install --ignore-platform-reqs

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # - name: Setup PHP with PECL extension
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.2'

      # - name: Setup Dependencies
      #   uses: "ramsey/composer-install@v2"

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
