name: Test Workflow

on: 
    push:
        branches:
            - '*'
            - '!master'
jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@master
        
      - name: Setup NPM
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Setup Dependencies
        uses: "ramsey/composer-install@v2"
  
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env          
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
